title: Plotly.vaadin.api
description: A Vaadin Add-On for drawing charts (area, arearange, areaspline, areasplinerange, columns, bars (horizontal columns), boxplot, bubble, donut, line, pie, spline and scatter) based on Plotly.js JavaScript Library
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
